# Generated by Django 3.1.5 on 2021-01-12 16:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='images'),
            preserve_default=False,
        ),
    ]
